djangoProject2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import  i18n_patterns
urlpatterns = [

    path('admin/', admin.site.urls),
    ]

urlpatterns += i18n_patterns(
    path('i18n/',include('django.conf.urls.i18n')),
    path('',include("index.urls")),
    path("research/", include("research.urls")),
    path("people/", include("people.urls")),
    path("projects/", include("projects.urls")),
    path("publications/", include("publications.urls")),
    path("teaching/", include("teaching.urls")),
    path("contact/", include("contact.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView

urlpatterns = [
    path('',HomeView.as_view(), name="home"),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
]

people/urls.py
from django.urls import path

from . import views
from .views import HomeView, ArticleDetailView



urlpatterns = [
    path('',HomeView.as_view(), name="people"),


    path('person/<int:pk>', ArticleDetailView.as_view(), name='person-detail'),
    # path('person/<int:pk>', views.home, name='home'),
]

people/models.py
import requests
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Person(models.Model):
    title = models.CharField(max_length=255)
    maisID = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=256, choices=[('Employee', 'Employee'), ('Student', 'Student'), ('Doctorand', 'Doctorand'), ('Uncategorized', 'Uncategorized') ])
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(null=True, blank=True, default='../static/profilePic.png')
    body = RichTextField(null = True)
    body_sk = RichTextField(null=True)

    def __str__(self):
        return self.title

projects/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User
from people.models import Person


class Pategory(models.Model):
    title = models.CharField(max_length=255)
    title_sk = models.CharField(max_length=255,null = True,blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=255)
    title_sk = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Pategory, on_delete=models.CASCADE, null=True)
    created_by = models.ManyToManyField(Person,blank=True)

    body = RichTextField(null=True)
    body_sk = RichTextField(null=True)

    def __str__(self):
        return self.title

publications/models.py
from django.db import models
from django.contrib.auth.models import User
from people.models import Person
from projects.models import Project
from research.models import Research



class Publication(models.Model):
    title = models.CharField(max_length=255, null=True)
    link = models.CharField(max_length=255, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_by = models.ManyToManyField(Person,blank=True)

    related_project = models.ManyToManyField(Project,blank=True)
    related_research = models.ManyToManyField(Research,blank=True)


    def __str__(self):
        return self.title

research/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth.models import User

from people.models import Person



class Research(models.Model):
    title = models.CharField(max_length=255)
    title_sk = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_by = models.ManyToManyField(Person, blank=True)
    body = RichTextField(null=True)
    body_sk = RichTextField(null=True)

    def __str__(self):
        return self.title

people/views.py
from django.views.generic import ListView, DetailView
from .models import Person
import requests


class HomeView(ListView):
    model = Person
    template_name = 'people/people.html'

class ArticleDetailView(DetailView):
    model = Person
    template_name = 'people/person_details.html'
    # print(str(model.maisID))

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        tmp = '@xxaq22'
        obj = Person.objects.all()
        for i in obj:
            field_object = Person._meta.get_field('id')
            field_value = field_object.value_from_object(i)
            if field_value == self.kwargs['pk']:
                field_object = Person._meta.get_field('maisID')
                tmp = field_object.value_from_object(i)

        # print(tmp)
        try:
            context['response'] = requests.get(
                "https://kpi:GWsy6BfLfc9rUB03tT6e@maisutils.tuke.sk/export/?vystup=rozvrh_pedagoga&login=" + tmp).json()
            x = requests.get(
            "https://kpi:GWsy6BfLfc9rUB03tT6e@maisutils.tuke.sk/export/?vystup=rozvrh_pedagoga&login=" + tmp).json()

        # y = json.loads(x)
        # print(x)
            subjects = []
            semester = []
            day = []
            room = []
            time1 = []
            time2 = []
            for i in x:
                # print(i)
                subjects.append(i['skratka_ps'])
                semester.append(i['semester'])
                day.append(i['den'])
                room.append(i['miestnost'])
                time1.append(i['cas1'])
                time2.append(i['cas2'])

            context['subjects'] = subjects
            context['semester'] = semester
            context['day'] = day
            context['room'] = room
            context['time1'] = time1
            context['time2'] = time2

        finally:
            return context

people/templates/people/people.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>

{% block MainHeader %}{%trans 'People' %}{% endblock %}


{% block content %}
<body class="d-flex flex-column min-vh-100">

<br>
<br>

<nav>
    <div class="nav nav-tabs text-center justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab"
           aria-controls="nav-home" aria-selected="true">{% trans 'Employees' %}</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab"
           aria-controls="nav-profile" aria-selected="false">{% trans 'Phd Students' %}</a>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab"
           aria-controls="nav-contact" aria-selected="false">{% trans 'Students' %}</a>
    </div>
</nav>




<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="row">
            {% for person in object_list %}
                {% if person.status == "Employee" %}

                <div class="col-12 col-md-4">
            <div class="card">
                {% if person.profile_pic.url is not None %}
{#                    <img class="card-img-top card_center" src="{{person.profile_pic.url}}" alt="Card image cap" width="50"#}
{#                     height="250">#}
                   <img class="rounded mx-auto d-block" src="{{ person.profile_pic.url }}" alt="Card image cap" width="300"
                 height="300">
                {% endif %}
                <div class="card-body card_center">
                    {% if person.title is not None %}
                    <h5 class="card-title card_center">{{ person.title }}</h5>
                    {% endif %}
{#                    <a href="{% url 'person-detail' person.pk %}" class="btn card_center btn-primary"><h5 class="card-title card_center">Profile</h5>#}
{#                        </a>#}
                                         <a class="btn btn-primary btn-lg" href="{% url 'person-detail' person.pk %}" role="button">{% trans 'Profile' %}</a>

                </div>

                </div>
                </div>
                {% endif %}
            {% endfor %}
     </div>
    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

            <div class="row">
            {% for person in object_list %}
                {% if person.status == "Doctorand" %}

                <div class="col-12 col-md-4">
            <div class="card">
                {% if person.profile_pic.url is not None %}
                     <img class="rounded mx-auto d-block" src="{{ person.profile_pic.url }}" alt="Card image cap" width="300"
                 height="300">
                {% endif %}
                <div class="card-body card_center">
                    {% if person.title is not None %}
                    <h5 class="card-title card_center">{{ person.title }}</h5>
                    {% endif %}
{#                    <a href="{% url 'person-detail' person.pk %}" class="btn card_center btn-primary"><h5 class="card_center card-title">Profile</h5>#}
{#                        </a>#}
                 <a class="btn btn-primary btn-lg" href="{% url 'person-detail' person.pk %}" role="button">{% trans 'Profile' %}</a>
                </div>

                </div>
                </div>
                {% endif %}
            {% endfor %}
     </div>
    </div>

    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
        <div class="row">
            {% for person in object_list %}
                {% if person.status == "Student" %}

                <div class="col-12 col-md-4">
            <div class="card card_center">
                {% if person.profile_pic.url is not None %}
                     <img class="rounded mx-auto d-block" src="{{ person.profile_pic.url }}" alt="Card image cap" width="300"
                 height="300">
                {% endif %}
                <div class="card-body card_center">
                    {% if person.title is not None %}
                    <h5 class="card-title card_center">{{ person.title }}</h5>
                    {% endif %}
{#                    <a href="{% url 'person-detail' person.pk %}" class="btn btn-primary card_center"><h5 class="card-title card_center">Profile</h5>#}
{#                        </a>#}
                 <a class="btn btn-primary btn-lg" href="{% url 'person-detail' person.pk %}" role="button">{% trans 'Profile' %}</a>
                </div>

                </div>
                </div>
                {% endif %}
            {% endfor %}
     </div>
    </div>
</div>
<br>
<br>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <div class="wrapper flex-grow-1"></div>
    </body>
</html>
{% endblock %}

people/templates/people/person_details.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
{% block MainHeader %}{% trans 'People' %}{% endblock %}

{% block content %}
    {% get_current_language as LANGUAGE_CODE %}
    <body class=" d-flex flex-column min-vh-100">


    <div class="article_detail">
        <h1 class="article_detail">{{ person.title }}</h1>
        <br>
        {% if  person.profile_pic.url is not None %}
            <img class="rounded mx-auto d-block" src="{{ person.profile_pic.url }}" alt="Card image cap" width="300"
                 height="300">
        {% endif %}
        <br><br>
        <p class="article_detail"> <br>
            <b>{% trans 'About: ' %}</b> <br>
            {% if LANGUAGE_CODE == 'en' %}
                {{ person.body  | safe }}
            {% endif %}
            {% if LANGUAGE_CODE == 'sk' %}
                {{ person.body_sk  | safe }}
            {% endif %}
            <b>{% trans 'Related publications: ' %}</b> <br>{{ person.publication_set.all|join:"  ,  " }} <br>
            <b>{% trans 'Related researches: ' %}</b> <br>{{ person.research_set.all|join:"  ,  " }} <br>
            <b>{% trans 'Related projects: ' %}</b>  <br>{{ person.project_set.all|join:"  ,  " }}
            <br><br>
            <b>{% trans 'Timetable: ' %}</b>
            {#    {{ room }}<br>#}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">{% trans 'Semester' %}</th>
                    <th scope="col">{% trans 'Subject' %}</th>
                    <th scope="col">{% trans 'Day' %}</th>
                    <th scope="col">{% trans 'Room' %}</th>
                    <th scope="col">{% trans 'Time' %}</th>

                </tr>
                </thead>
                <tbody>

                {% for i in response %}

                    <tr>
                        <td>{{ semester.pop }}</td>
                        <td>{{ subjects.pop }}</td>
                        <td>{{ day.pop }}</td>
                        <td>{{ room.pop }}</td>
                        <td>{{ time1.pop }} , {{ time2.pop }}</td>

                    </tr>

                {% endfor %}
                </tbody>
            </table>
        </div>
        <a class="btn btn-primary btn-lg" href="/people" role="button">{% trans 'Back' %}</a>

        </p>
    </div>

    <br>
    <br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>

    <div class="wrapper flex-grow-1"></div>
    </body>
    </html>
{% endblock %}